### ISSUE TITLE
Failure to mount storage account in pod when --default-working-dir is not specified in Azure Redhat Openshift

### ISSUE THREAD

**Issue by vivekjain007** [kubernetes-sigs/blob-csi-driver#1141]
**What happened**:
Pod shows failure in mounting the volume with log message  [mkdir /.blobfuse2: operation not permitted] with fuse2 protocol when
--default-working-dir mount option is not specified.

When --default-working-dir=/tmp/blobfuse2workdir is specified as mount options then pod is able to mount the storage account without any error.

**What you expected to happen**:
Not specifying --default-working-dir as mount option shall use the default location without any error while mounting the storage account in pod.

**How to reproduce it**:
Deployed blob-csi-driver version 1.23.2 with blobfuseproxy enabled using helm chart in Azure Redhat Openshift cluster version 4.12.x. Create storage class with fuse2 protocol and persistent volume claim and persistent volume. Deploy pod with volume mount using the persistent volume. 

**Anything else we need to know?**:
Pod logs attached.
[mount_failure.log](https://github.com/kubernetes-sigs/blob-csi-driver/files/13486808/mount_failure.log)

**Environment**:
Azure Redhat Openshift version 4.12.x
blob csi driver helm chart version 1.23.2

**Comment by andyzhangx** [comment]
@vivekjain007 does `/var/log/` folder exists on Azure Redhat Openshift?

**Comment by andyzhangx** [comment]
o, the blobfuse2 driver does not have permission to create `/var/log/blobfuse2.log` file
```
failed to create default work dir [mkdir /.blobfuse2: operation not permitted]
```

**Comment by vivekjain007** [comment]
@andyzhangx  /var/log folder does exists on Azure Redhat Openshift nodes. Looks like the $HOME value is not populated properly though "$HOME/.blobfuse2" in Azure Redhat Openshift.
https://github.com/Azure/azure-storage-fuse/blob/e6872559290b57cd961e0601572329815c55fa75/common/types.go#L82
Hope this helps

**Comment by andyzhangx** [comment]
@souravgupta-msft @vibhansa-msft could you take a look at this issue? blobfuse2 already works on coreos, this is a non-blocking issue, thanks

**Comment by souravgupta-msft** [comment]
@andyzhangx, we have merged the PR for fixing this issue in blobfuse2, https://github.com/Azure/azure-storage-fuse/pull/1296. It will be part of the next release.

**Comment by andyzhangx** [comment]
@souravgupta-msft thanks for the quick fix! this issue would be fixed in blobfuse 2.1.3

**Comment by vivekjain007** [comment]
Thanks Andy and team

**Comment by adityagu0910** [comment]
Hey @vivekjain007 @andyzhangx 
I am still seeing this issue in version deployed in my OpenShift cluster running on azure vms (blob-csi-driver-1.25.0). Could you please suggest how to make it work?

`MountVolume.MountDevice failed for volume "ocp4-etcd-backup-pv" : rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: failed to create default work dir [mkdir /.blobfuse2: operation not permitted] , output: Please refer to http://aka.ms/blobmounterror for possible causes and solutions for mount errors.`

**Comment by andyzhangx** [comment]
@vivekjain007 what is your blobfuse2 version on the node? are you using blobfuse-proxy? can you provide the blob csi driver logs on the node, follow by: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by adityagu0910** [comment]
@andyzhangx 
BLOBFUSE2_VERSION:       2.3.2
Yes blobfuse-proxy is being used by default. attached my sc, pv and pvc definitions.
[sc_pv_pvc.yaml.txt](https://github.com/user-attachments/files/17942048/sc_pv_pvc.yaml.txt)

**Comment by adityagu0910** [comment]
this is what i see in logs 

`
I1128 02:44:19.872297 3677826 utils.go:104] GRPC call: /csi.v1.Node/NodeStageVolume
I1128 02:44:19.872434 3677826 utils.go:105] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/5bb7823aced96c4747daf97d128c9c87181028d168c346856086c779a46/globalmount","volume_capability":{"AccessType":{"Mount":{"volume_mount_group":"1000870000"}},"access_mode":{"mode":5}},"volume_context":{"containername":"mycontainername","resourceGroup":"azureresourcegroupname","secretName":"blob-storage-secret","secretNamespace":"kube-system","storageAccount":"mystorageaccountname"},"volume_id":"azureresourcegroupname#mystorageaccountname#mycontainername"}
I1128 02:44:19.873256 3677826 blob.go:544] volumeID(azureresourcegroupname#mystorageaccountname#mycontainername) authEnv: []
I1128 02:44:19.902464 3677826 blob.go:951] got storage account(mystorageaccountname) from secret(blob-storage-secret) namespace(kube-system)
I1128 02:44:19.902525 3677826 nodeserver.go:409] append volumeMountGroup 1000870000
I1128 02:44:19.902573 3677826 nodeserver.go:424] target /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/5bb7823aced96c4747daf97d128c9c87181028d168c346856086c779a46/globalmount protocol  volumeId azureresourcegroupname#mystorageaccountname#mycontainername
mountflags []
mountOptions [-o gid=1000870000 --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/azureresourcegroupname#mystorageaccountname#mycontainername --container-name=mycontainername] volumeMountGroup 1000870000
args /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/5bb7823aced96c4747daf97d128c9c87181028d168c346856086c779a46/globalmount -o gid=1000870000 --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/azureresourcegroupname#mystorageaccountname#mycontainername --container-name=mycontainername
serverAddress mystorageaccountname.blob.core.windows.net
I1128 02:44:19.902609 3677826 nodeserver.go:166] start connecting to blobfuse proxy, protocol: , args: /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/5bb7823aced96c4747daf97d128c9c87181028d168c346856086c779a46/globalmount -o gid=1000870000 --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/azureresourcegroupname#mystorageaccountname#mycontainername --container-name=mycontainername
I1128 02:44:19.903810 3677826 nodeserver.go:175] begin to mount with blobfuse proxy, protocol: , args: /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/5bb7823aced96c4747daf97d128c9c87181028d168c346856086c779a46/globalmount -o gid=1000870000 --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/azureresourcegroupname#mystorageaccountname#mycontainername --container-name=mycontainername
E1128 02:44:19.938211 3677826 nodeserver.go:178] GRPC call returned with an error:rpc error: code = Unknown desc = exit status 1 Error: failed to create default work dir [mkdir /.blobfuse2: operation not permitted]
E1128 02:44:19.938431 3677826 nodeserver.go:450] rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: failed to create default work dir [mkdir /.blobfuse2: operation not permitted]
 `

**Comment by andyzhangx** [comment]
from this PR: https://github.com/Azure/azure-storage-fuse/pull/1296, if you set `HOME` env var on the node, that would create blobfuse2 dir on another dir, that may work

**Comment by adityagu0910** [comment]
but seems this PR was merged, right ?
OpenShift recommends to not modify the nodes manually so do not want to try that.
Can I set to create this blobfuse2 directory to some different path in mount options of my PV ?

**Comment by souravgupta-msft** [comment]
You can use `--default-working-dir` mount option to provide this.
We had fixed this issue where if $HOME environment variable is not present, it uses the current working directory as the default working directory. In this case, I think that the current working directory is pointing to the root directory, so it is resolving to `/.blobfuse2`.

**Comment by vivekjain007** [comment]
Hi Andy,I am no longer with bosch and do not have access to the openshift env there. You can try reaching out to Ge Gao.Warm regards Vivek JainOn 28-Nov-2024 7:57 am, Andy Zhang ***@***.***> wrote:
@vivekjain007 what is your blobfuse2 version on the node? are you using blobfuse-proxy? can you provide the blob csi driver logs on the node, follow by: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by adityagu0910** [comment]
@souravgupta-msft I tried adding below option but pvc is not getting mounted to pod. I do not see any error in blob container (of pod csi-blob-node-xxxx)and it says mount succeeded  and i can see volume created on OpenShift worker node.
`  mountOptions:
    - --default-working-dir=/tmp`

But I see fs like below inside my pod and I can not do any operation related to this fs.
d??????????   ? ?    ?             ?            ? backup

could it be some permission issue ? where can i check the logs?

**Comment by adityagu0910** [comment]
I noticed when pod is running with root user then it is able to mount.
is there specific mount option that we can provide so pod running with specific OpenShift restricted uid and gid can also able to mount ?

**Comment by adityagu0910** [comment]
It worked with below options 
  mountOptions:
--default-working-dir=/tmp
 -o allow_other

**Comment by andyzhangx** [comment]
thanks for the confirm
